apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: {{ .Values.auth_service.replicas }}
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      annotations:
        prometheus.io/port: "9000"
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: {{ .Values.auth_service.image.name }}
        resources:
          limits:
            memory: "512Mi"
            cpu: "400m"
        ports:
        - containerPort: 9000
        env:
          - name: NODE_LOCAL_PORT
            value: "9000"
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: jwt
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: url
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://${HOST_IP}:4317
          - name: OTEL_SERVICE_NAME
            value: "auth_service"   
