apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweet-deployment
  labels:
    app: tweet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tweet
  template:
    metadata:
      annotations:
        prometheus.io/port: "8081"
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
      labels:
        app: tweet
    spec:
      containers:
      - name: tweet
        image: youssefjj/twitter-clone-tweet-service_v2:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "400m"
        ports:
        - containerPort: 8081
        env:
          - name: AUTH_HOST
            value: "auth-service"
          - name: AUTH_PORT
            value: "80"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: url 
          - name: NODE_LOCAL_PORT
            value: "8081"
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://$(HOST_IP):4318
          - name: OTEL_SERVICE_NAME
            value: "tweet_service"
