apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweet-deployment
  labels:
    app: tweet
spec:
  replicas: {{ .Values.tweet_service.replicas }}
  selector:
    matchLabels:
      app: tweet
  template:
    metadata:
      annotations:
        prometheus.io/port: "8081"
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
      labels:
        app: tweet
    spec:
      containers:
      - name: tweet
        image: {{ print .Values.tweet_service.image.name ":" .Values.tweet_service.image.tag }}
        resources:
          limits:
            memory: "512Mi"
            cpu: "400m"
        ports:
        - containerPort: 8081
        env:
          - name: AUTH_HOST
            value: "auth-service"
          - name: AUTH_PORT
            value: "80"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: url 
          - name: NODE_LOCAL_PORT
            value: "8081"
